---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
<<<<<<< HEAD
        run: docker-compose down;docker-compose run --rm app sh -c "python manage.py wait_for_db"
=======
        run: docker-compose down;docker-compose run --rm app sh -c "python manage.py runserver 0.0.0.0:8000"
>>>>>>> parent of ccb9e00 (added network net1 2)
      - name: Lint
        run: docker-compose down;docker-compose run --rm app sh -c "flake8"
